NRM1-HastaneOtomasyon/Areas/Admin/Controllers/ManagerController.cs
using Hastane.Business.Models.DTOs;
using Hastane.Business.Services.AdminService;
using Microsoft.AspNetCore.Mvc;

namespace NRM1_HastaneOtomasyon.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ManagerController : Controller
    {
        private readonly IAdminService _adminService;
        public ManagerController(IAdminService adminService)
        {
            _adminService = adminService;
        }
        public IActionResult AddManager()
        {
            return View(); //Burası yönetici ekleme sayfasını açacak olan HttpGet!!
        }

        [HttpPost]
        public async Task<IActionResult> AddManager(AddManagerDTO addManagerDTO)
        {

            if (ModelState.IsValid)
            {
                await _adminService.AddManager(addManagerDTO);
                return RedirectToAction("ListOfManagers");
            }

            return View(addManagerDTO);
        }

        public async Task<IActionResult> ListOfManagers()
        {
            var managerList = await _adminService.ListOfManager();
            return View(managerList);

        }
        public async Task<IActionResult> UpdateManager(Guid id)
        {
            var updateManeger= await _adminService.GetManager(id);
            return View(updateManeger);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateManager(UpdateManagerDTO updateManagerDTO)
        {
            await _adminService.UpdateManager(updateManagerDTO);
            return RedirectToAction(nameof(ListOfManagers));
        }
    }
}

NRM1-HastaneOtomasyon/Areas/Admin/Views/Manager/AddManager.cshtml
@model AddManagerDTO

@{
    ViewData["Title"] = "AddManager";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>AddManager</h1>

<h4>Manager</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddManager">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Surname" class="control-label"></label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Salary" class="control-label"></label>
                <input asp-for="Salary" class="form-control" />
                <span asp-validation-for="Salary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmailAddress" class="control-label"></label>
                <input asp-for="EmailAddress" class="form-control" />
                <span asp-validation-for="EmailAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

NRM1-HastaneOtomasyon/Areas/Admin/Views/Manager/ListOfManagers.cshtml
@model IEnumerable<ListOfManagersVM>
@{
    ViewData["Title"] = "ListOfManager";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>ListOfManagers</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Surname
            </th>
            <th>
                EmailAddress
            </th>
            <th>
                Roles
            </th>
            <th>
                Salary
            </th>
            <th>
                Function
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
                <tr>
                    <td>
                        @item.Name
                    </td>
                    <td>
                        @item.Surname
                    </td>
                    <td>
                        @item.EmailAddress
                    </td>
                    <td>
                        @item.Roles
                    </td>
                    <td>
                        @item.Salary
                    </td>
                    <td>
                        <a class="btn btn-success" asp-area="Admin" asp-controller="Manager" asp-action="UpdateManager" asp-route-id="@item.ID">Update</a>
                        @*<a class="btn btn-danger" asp-action="DeletedManager" asp-route-id="@item.ID">Delete</a>*@
                    </td>
                </tr>  
        }
    </tbody>
</table>

NRM1-HastaneOtomasyon/Areas/Admin/Views/Manager/UpdateManager.cshtml
@model UpdateManagerDTO

@{
    ViewData["Title"] = "UpdateManager";
     Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>UpdateManager</h1>

<h4>Manager</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="UpdateManager">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Surname" class="control-label"></label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmailAddress" class="control-label"></label>
                <input asp-for="EmailAddress" class="form-control" />
                <span asp-validation-for="EmailAddress" class="text-danger"></span>
            </div>  
            <div class="form-group">
                <label asp-for="Salary" class="control-label"></label>
                <input asp-for="Salary" class="form-control" />
                <span asp-validation-for="Salary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdentityNumber" class="control-label"></label>
                <input asp-for="IdentityNumber" class="form-control" />
                <span asp-validation-for="IdentityNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>